version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-data
    versions:
    - 3.23.0
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
    - 3.25.0
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: ember-metrics
    versions:
    - 1.0.0
    - 1.1.0
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: video.js
    versions:
    - 7.10.2
  - dependency-name: js-yaml
    versions:
    - 3.14.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
