---
language: node_js
node_js:
  - "10"

os: linux
arch: arm64
dist: xenial

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # Reduce ember's parallel-ness to 2,
    # the number of cores available on travis.
    # See the following for details:
    # https://git.io/vdao3
    # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
    - JOBS=2

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

jobs:
  include:
    - stage: Tests
      name: Lint
      script:
        - yarn lint:js
        # - yarn lint:hbs
    - script: yarn coverage && bash <(curl -s https://codecov.io/bash)
      name: Test & Upload Coverage
    - script:
        - yarn global add @lhci/cli@0.4.x
        - yarn build --environment=production
        - lhci autorun --upload.target=temporary-public-storage
      name: Create lighthouse report
