---
language: node_js
node_js:
  - "10"

os: linux
dist: xenial

addons:
  chrome: stable

cache: yarn

env:
  global:
    # Reduce ember's parallel-ness to 2,
    # the number of cores available on travis.
    # See the following for details:
    # https://git.io/vdao3
    # https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
    - JOBS=2

install:
  - yarn install --non-interactive

jobs:
  include:
    - stage: Tests
      name: Lint
      script:
        - yarn lint:js
        # - yarn lint:hbs
    - script:
        - yarn coverage
        - bash <(curl -s https://codecov.io/bash)
      if: branch = master
      name: Test & Upload Coverage
    - script:
        - yarn global add @lhci/cli@0.4.x
        - mkdir lhci
        - yarn build --environment=production
        - lhci autorun --config-path=config/lighthouserc.js --upload.target=temporary-public-storage
      name: Create Lighthouse Report
