---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

jobs:
  include:
    - stage: Tests
      name: Lint
      script:
        - yarn lint:js
        # - yarn lint:hbs
    - script: yarn coverage && bash <(curl -s https://codecov.io/bash)
      name: Test & Upload Coverage
    - script:
        - yarn global install @lhci/cli@0.4.x
        - yarn build --environment=production
        - lhci autorun --upload.target=temporary-public-storage
      name: Create lighthouse report
